// <auto-generated />
using System;
using Dgii.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dgii.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220225161807_create_table_registros")]
    partial class create_table_registros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dgii.DataClasses.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadRegistros")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("FechaComprobante")
                        .HasColumnType("int");

                    b.Property<int>("FechaPago")
                        .HasColumnType("int");

                    b.Property<int>("FormaPago")
                        .HasColumnType("int");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<int>("IdCarga")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificacionProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Isc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IsrPercibido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisFacturado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisPercibido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisPorAdelantar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisProporcionado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisRetenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoBienes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIsr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPropina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoServicios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ncf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtrosImpuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("TipoComprado")
                        .HasColumnType("int");

                    b.Property<int>("TipoIsr")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFacturado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
